# Giodimagio: Mi entorno de desarrollo local
name: ${COMPOSE_PROJECT_NAME}
x-anchors:
  volumes_default:
    - &host_timezone ${HOST_TIMEZONE_PATH}:/etc/timezone:ro
    - &host_localtime ${HOST_LOCALTIME_PATH}:/etc/localtime:ro
services:
  nginx-proxy-manager:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx-proxy-manager-service
    restart: unless-stopped
    networks:
      - nginx-proxy-manager_network_default
    ports:
      - ${APP_PORT_ADMIN}:81
      - ${APP_PORT_HTTP}:80
      - ${APP_PORT_HTTPS}:443
    volumes:
      - *host_timezone
      - *host_localtime
      - nginx_proxy_manager_data:/data
      - nginx_proxy_manager_letsencrypt:/etc/letsencrypt
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer-service
    restart: unless-stopped
    networks:
      - nginx-proxy-manager_network_default
    volumes:
      - *host_timezone
      - *host_localtime
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - portainer_data:/data
  gitlab:
    image: 'gitlab/gitlab-ce:latest'
    container_name: gitlab-service
    restart: unless-stopped
    networks:
      - nginx-proxy-manager_network_default
    volumes:
      - gitlab_config:/etc/gitlab
      - gitlab_logs:/var/log/gitlab
      - gitlab_data:/var/opt/gitlab
    shm_size: '256m'
networks:
  nginx-proxy-manager_network_default:
    name: nginx-proxy-manager_network_default
    external: true
volumes:
  portainer_data:
    name: portainer_data
  nginx_proxy_manager_data:
    name: nginx_proxy_manager_data
  nginx_proxy_manager_letsencrypt:
    name: nginx_proxy_manager_letsencrypt
  gitlab_config:
    name: gitlab_config
  gitlab_logs:
    name: gitlab_logs
  gitlab_data:
    name: gitlab_data
